/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmitCard {
  'id' : bigint,
  'postedDate' : bigint,
  'downloadLink' : string,
  'isActive' : boolean,
  'examBoard' : string,
  'examDate' : string,
  'examName' : string,
}
export interface Job {
  'id' : bigint,
  'title' : string,
  'postedDate' : bigint,
  'officialLink' : string,
  'vacancies' : bigint,
  'isActive' : boolean,
  'category' : string,
  'organization' : string,
  'department' : string,
  'lastDate' : string,
  'qualification' : string,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'postedDate' : bigint,
  'link' : string,
  'description' : string,
  'isActive' : boolean,
}
export interface Result {
  'id' : bigint,
  'title' : string,
  'postedDate' : bigint,
  'officialLink' : string,
  'isActive' : boolean,
  'examBoard' : string,
  'resultDate' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdmitCard' : ActorMethod<[string, string, string, string], AdmitCard>,
  'createJob' : ActorMethod<
    [string, string, string, string, bigint, string, string, string],
    Job
  >,
  'createNotification' : ActorMethod<
    [string, string, string, string],
    Notification
  >,
  'createResult' : ActorMethod<[string, string, string, string], Result>,
  'deleteAdmitCard' : ActorMethod<[bigint], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'deleteNotification' : ActorMethod<[bigint], undefined>,
  'deleteResult' : ActorMethod<[bigint], undefined>,
  'getActiveAdmitCards' : ActorMethod<[], Array<AdmitCard>>,
  'getActiveJobs' : ActorMethod<[], Array<Job>>,
  'getActiveNotifications' : ActorMethod<[], Array<Notification>>,
  'getActiveResults' : ActorMethod<[], Array<Result>>,
  'getAdmitCard' : ActorMethod<[bigint], AdmitCard>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[bigint], Job>,
  'getNotification' : ActorMethod<[bigint], Notification>,
  'getResult' : ActorMethod<[bigint], Result>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchJobsByCategory' : ActorMethod<[string], Array<Job>>,
  'searchJobsByKeyword' : ActorMethod<[string], Array<Job>>,
  'updateAdmitCard' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    AdmitCard
  >,
  'updateJob' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      boolean,
    ],
    Job
  >,
  'updateNotification' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    Notification
  >,
  'updateResult' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];