/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmitCard = IDL.Record({
  'id' : IDL.Nat,
  'postedDate' : IDL.Int,
  'downloadLink' : IDL.Text,
  'isActive' : IDL.Bool,
  'examBoard' : IDL.Text,
  'examDate' : IDL.Text,
  'examName' : IDL.Text,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedDate' : IDL.Int,
  'officialLink' : IDL.Text,
  'vacancies' : IDL.Nat,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'organization' : IDL.Text,
  'department' : IDL.Text,
  'lastDate' : IDL.Text,
  'qualification' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'postedDate' : IDL.Int,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Result = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedDate' : IDL.Int,
  'officialLink' : IDL.Text,
  'isActive' : IDL.Bool,
  'examBoard' : IDL.Text,
  'resultDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdmitCard' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AdmitCard],
      [],
    ),
  'createJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Job],
      [],
    ),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Notification],
      [],
    ),
  'createResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'deleteAdmitCard' : IDL.Func([IDL.Nat], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [], []),
  'deleteResult' : IDL.Func([IDL.Nat], [], []),
  'getActiveAdmitCards' : IDL.Func([], [IDL.Vec(AdmitCard)], ['query']),
  'getActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getActiveNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getActiveResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getAdmitCard' : IDL.Func([IDL.Nat], [AdmitCard], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [Job], ['query']),
  'getNotification' : IDL.Func([IDL.Nat], [Notification], ['query']),
  'getResult' : IDL.Func([IDL.Nat], [Result], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'searchJobsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'updateAdmitCard' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [AdmitCard],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [Job],
      [],
    ),
  'updateNotification' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Notification],
      [],
    ),
  'updateResult' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmitCard = IDL.Record({
    'id' : IDL.Nat,
    'postedDate' : IDL.Int,
    'downloadLink' : IDL.Text,
    'isActive' : IDL.Bool,
    'examBoard' : IDL.Text,
    'examDate' : IDL.Text,
    'examName' : IDL.Text,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedDate' : IDL.Int,
    'officialLink' : IDL.Text,
    'vacancies' : IDL.Nat,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'organization' : IDL.Text,
    'department' : IDL.Text,
    'lastDate' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'postedDate' : IDL.Int,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Result = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedDate' : IDL.Int,
    'officialLink' : IDL.Text,
    'isActive' : IDL.Bool,
    'examBoard' : IDL.Text,
    'resultDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdmitCard' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AdmitCard],
        [],
      ),
    'createJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Job],
        [],
      ),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Notification],
        [],
      ),
    'createResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'deleteAdmitCard' : IDL.Func([IDL.Nat], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [], []),
    'deleteResult' : IDL.Func([IDL.Nat], [], []),
    'getActiveAdmitCards' : IDL.Func([], [IDL.Vec(AdmitCard)], ['query']),
    'getActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getActiveNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getActiveResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getAdmitCard' : IDL.Func([IDL.Nat], [AdmitCard], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [Job], ['query']),
    'getNotification' : IDL.Func([IDL.Nat], [Notification], ['query']),
    'getResult' : IDL.Func([IDL.Nat], [Result], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'searchJobsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'updateAdmitCard' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [AdmitCard],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [Job],
        [],
      ),
    'updateNotification' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Notification],
        [],
      ),
    'updateResult' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };